### ISSUE TITLE
后续有支持hevc的计划吗？

### ISSUE THREAD

**Issue by jiangshao1998** [shady-xia/flvExtend#1]

**Comment by shady-xia** [comment]
没有，因为只是对`flv.js`的一些问题进行了扩展优化

**Comment by jiangshao1998** [comment]
我认为b站现在的js代码已经支持了hevc的硬解，但是不知道应该如何调用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月19日(星期二) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shady-xia/flvExtend] 后续有支持hevc的计划吗？ (Issue #1)





 
没有，因为只是对flv.js的一些问题进行了扩展优化

**Comment by shady-xia** [comment]
mpegts.js 已经支持hevc
