### ISSUE TITLE
无法监听到视频事件

### ISSUE THREAD

**Issue by zym0110** [shady-xia/flvExtend#10]
![image](https://user-images.githubusercontent.com/48800373/207574176-d608efd2-c293-4c50-9aeb-819dde89e02f.png)
 // 配置需要的功能
        const flv = new FlvExtend({
          element: this.videoRef, // *必传
          frameTracking: true, // 开启追帧设置
          updateOnStart: true, // 点击播放后更新视频
          updateOnFocus: true, // 获得焦点后更新视频
          reconnect: true, // 开启断流重连
          reconnectInterval: 2000, // 断流重连间隔(ms)
          trackingDelta: 2, // 追帧最大延迟
        });
        // 调用 init 方法初始化视频
        // init 方法的参数与 flvjs.createPlayer 相同，并返回 flvjs.player 实例
        this.playerIns = flv.init(
          {
            type: "flv",
            url: this.props.videoUrl,
            isLive: true,
          },
          {
            enableStashBuffer: false, // 是否启用IO隐藏缓冲区。如果您需要实时（最小延迟）来进行实时流播放，则设置为false
            autoCleanupSourceBuffer: true, // 对SourceBuffer进行自动清理
            stashInitialSize: 128, // 减少首帧显示等待时长
          }
        );
        this.playerIns.on("play", (e: any) => {
            console.log("play", e);
          });

作者您好，这里得视频播放事件无法打印，也就意味监听功能失效

**Comment by XiaotaoTTTtian** [comment]
flv.js里面好像没有这个事件。用下面这种方法，之间监听这个元素的播放事件
this.videoElement.addEventListener('play', () => {
        // Do something
 })

**Comment by XiaotaoTTTtian** [comment]
flv.js里面好像没有这个事件。用下面这种方法，直接监听这个元素的播放事件
this.videoElement.addEventListener('play', () => {
        // Do something
 })

**Comment by shady-xia** [comment]
楼上正解，flv没有提供这些事件api，不过可以直接监听video元素的原生事件

**Comment by zym0110** [comment]
> flv.js里面好象没有这个东西。用下面这种方法，直接监听这个元素的播放 器this.videoElement.addEventListener('play', () => { // Do something })

感谢，确实可以

**Comment by zym0110** [comment]
> 楼上正解，flv没有提供这些事情api，不过可以直接监听video元素的原生事件

感谢感谢，这个可以关了
