### ISSUE TITLE
播放器闪屏

### ISSUE THREAD

**Issue by Yorlg** [shady-xia/flvExtend#11]
控制台报错如下：

 视频ERROR：  MediaError
flvExtend.js?952a:11051 [MSEController] > Failed to execute 'appendBuffer' on 'SourceBuffer': The HTMLMediaElement.error attribute is not null.

然后播放器就开始闪 过了一会就好了，这种情况请问一下要怎么解决呢

**Comment by shady-xia** [comment]
https://github.com/bilibili/flv.js/issues/334
https://github.com/bilibili/flv.js/issues/571
看起来像是硬件加速的问题，好像关掉就好了

**Comment by ljl-wanfanjdt** [comment]
除了关系硬件加速呢，还有什么方法
