### ISSUE TITLE
请问这个支持 mpegts.js 吗？

### ISSUE THREAD

**Issue by Smecta** [shady-xia/flvExtend#16]
https://github.com/xqq/mpegts.js
这个是基于flvjs的，现在已经升级了这个，还可以用这个扩展吗？

**Comment by shady-xia** [comment]
可以用的， 我自己的项目中就是用的mpegts搭配这个插件，唯一区别就是追帧使用mpegts的设置就行了

**Comment by Smecta** [comment]
是这样的，我这个项目里面 有flv还有mpegts，flv我没uninstall 看了使用说明 我怎么知道它是用的mpegts 还是flv 呀？

**Comment by shady-xia** [comment]
哦，sorry，因为插件引的是` import flvjs from 'flv.js'` 而不是 `import flvjs from 'mpegts.js'`，所以现在的插件直接用并不能支持mpegts.js，我是在本地改了下。急着用的话可以把源码down下来，把引入的插件改成 ` 'mpegts.js'`就可以了。后面我会做下兼容

**Comment by Smecta** [comment]
明白了,非常感谢🙏
还有一个问题，跟stuck有关，如果这个decodedFrames 与自己上次的记录的值 发生相等频繁，那就说明这个流断开了，那是不是就是后端他们推流的问题啊？但是我怎么去找（甩锅给）后端去检查啊？后端总说他们已经做了很好的优化了，有问题就是前端去优化😓....

**Comment by shady-xia** [comment]
> 明白了,非常感谢🙏 还有一个问题，跟stuck有关，如果这个decodedFrames 与自己上次的记录的值 发生相等频繁，那就说明这个流断开了，那是不是就是后端他们推流的问题啊？但是我怎么去找（甩锅给）后端去检查啊？后端总说他们已经做了很好的优化了，有问题就是前端去优化😓....

你说出了我的心声，这个也是我现在想找的答案，因为对于视频来说前端可控制的地方太少了，播不了就会被甩锅是前端问题，但是具体什么原因，因为不是主攻视频这块，所以比较没话语权，挺无解的

**Comment by shady-xia** [comment]
而且前端也做不了太多优化

**Comment by shady-xia** [comment]
Resolved, v0.2.0版本已迁移到 `mpegts.js`
