### ISSUE TITLE
传入url遇到的了一个报错的问题

### ISSUE THREAD

**Issue by Smecta** [shady-xia/flvExtend#17]
问题描述：
` [IOController] > Loader error, code = -1, msg = Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from /live/129.flv?key=8857f64203a7aa4a3e2aa235feceaf54
[TransmuxingController] > IOException: type = Exception, code = -1, msg = Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from /live/129.flv?key=8857f64203a7aa4a3e2aa235feceaf54 `
<img width="588" alt="image" src="https://github.com/shady-xia/flvExtend/assets/30615458/604daa9b-1152-4cce-a25b-2b9af8465f38">

是这样的，在开发环境我在前端配置了proxyTable 前端代理
```
"/live": {
    target: "https://192.168.228.132:8090/",
    secure: false,
    pathRewrite: {
      "^/live": "/live",
    },
  },
```
我在给它传递的url是 ` /live/129.flv?key=8857f64203a7aa4a3e2aa235feceaf54 ` 它就出现以上的报错，请问该怎么解决？
如果我传递完整的url,则会提示我cors跨域的报错，现在怎么办啊？

**Comment by shady-xia** [comment]
这里需要传递完整的url。跨域让服务端处理一下，配置下header支持CORS或者做个反向代理

**Comment by Smecta** [comment]
好的
