### ISSUE TITLE
这个是为啥呢

### ISSUE THREAD

**Issue by burialz** [shady-xia/flvExtend#2]
TypeError: this._mediaElement.play is not a function

**Comment by shady-xia** [comment]
能贴一下你的代码么

**Comment by jxh-0514** [comment]
我也是这样哎，请问怎么解决啊

**Comment by shady-xia** [comment]
必须用 `video` 标签
 `<video id="videoElement" controls autoplay></video>`

**Comment by jxh-0514** [comment]
> 必须用`video`标签 `<video id="videoElement" controls autoplay></video>`

好的，已成功，谢谢！
