### ISSUE TITLE
在主页面有两个flv播放器实例，跳转到两个播放器中的一个实例时报错。跳转之前先销毁了主页两个实例

### ISSUE THREAD

**Issue by XiaotaoTTTtian** [shady-xia/flvExtend#4]
![Dingta](https://user-images.githubusercontent.com/105273776/196870004-03e2eb4f-19b6-4f8c-b3fe-2716d369647b.jpg)

**Comment by shady-xia** [comment]
没太看明白，先销毁之前的两个实例，然后（跳转到两个播放器中的一个实例时报错），这个跳转是什么意思？这个时候有重新新建实例吗

**Comment by XiaotaoTTTtian** [comment]
已经解决了，当时直接调用的flv.js的销毁实例。后来用你在插件里写的销毁实例方法就好了。不好意思
