### ISSUE TITLE
关于断线重连的问题

### ISSUE THREAD

**Issue by goodtogood** [shady-xia/flvExtend#5]
你好，断线重连是指的前端网络断开吗？
如果是推流意外断开2秒后继续推流，这时可以自动重连吗？
除了流地址，现在用demo中默认代码，无法实现自动重连，
谢谢！

**Comment by shady-xia** [comment]
只要视频播放出现问题就会进入到flv.js的ERROR事件里，从而进行重连操作
demo页应该是重连的间隔事件设的太长了，我改了下，你可以再试试

**Comment by goodtogood** [comment]
修改重连时间后，不知道为何还是未触发重连事件，
测试浏览器为chrome和firefox，windows10
感谢解答！
`reconnectInterval: 0 `

**Comment by shady-xia** [comment]
目前手头没有推流的环境，我研究下

**Comment by jm821323** [comment]
清晰度切换了几次，第六次HTTP的fetch请求变成pending，一只pending中，其实现在流还是推送的，ios，微信h5页面，请问怎么解决，而且控制台一直提示卡住，重建视频。谢谢

**Comment by goodtogood** [comment]
@shady-xia 

网络请求及控制台输出如图


正常播放

![正常播放](https://user-images.githubusercontent.com/10088733/197203229-eaba126f-0dab-4e44-bebe-86b49df9a5ff.jpg)

推流停止后恢复，无变化
![推流停止后恢复，无变化](https://user-images.githubusercontent.com/10088733/197203310-472c70e5-61dd-4cac-9ab4-4e568d7f0280.jpg)


控制台

![控制台](https://user-images.githubusercontent.com/10088733/197203545-80151e58-b9e5-4882-9c3d-73564ca7e14e.jpg)

**Comment by shady-xia** [comment]
截图没看出来有什么问题。。

**Comment by goodtogood** [comment]
是的，除了没自动重新连接，没什么其它异常。
我可以提供一个重现环境，您如果有兴趣可以看一下，
如果需要ssh，请留下邮箱，稍后发你。
```

本repo代码  http://43.143.125.128:38080/demo/
推流地址 rtmp://43.143.125.128:31935/demo/test
播放地址 http://43.143.125.128:38080/demo/test.live.flv
           ws://43.143.125.128:38080/demo/test.live.flv
          rtsp://43.143.125.128:31935/demo/test
```

**Comment by shady-xia** [comment]
> 

方便的话直接加我qq吧，499650191
