### ISSUE TITLE
切换清晰度，flv一直pending中，控制台一直提示卡住重建视频

### ISSUE THREAD

**Issue by jm821323** [shady-xia/flvExtend#6]
清晰度切换了几次，第六次HTTP的fetch请求变成pending，一只pending中，其实现在流还是推送的，ios，微信h5页面，请问怎么解决，而且控制台一直提示卡住，重建视频。谢谢

**Comment by shady-xia** [comment]
1、浏览器http1的同源限制，同源下的http请求同时最多只能有6个，多出来的会pending
2、你切清晰度后，还增加了请求，说明之前的请求没释放掉，建议切换后把之前的实例释放掉，保证请求资源不会被浪费~

**Comment by SouthernPL** [comment]
> 1、浏览器http1的同源限制，同源下的http请求同时最多只能有6个，多出来的会pending 2、你切清晰度后，还增加了请求，说明之前的请求没释放掉，建议切换后把之前的实例释放掉，保证请求资源不会被浪费~

http1同源请求不能超过6 确实太坑了 如果同时播放8路视频 还做不到。
如何把http1 升级为http2 是需要在转发直播流的服务器上做设置吗

**Comment by shady-xia** [comment]
> > 1、浏览器http1的同源限制，同源下的http请求同时最多只能有6个，多出来的会pending 2、你切清晰度后，还增加了请求，说明之前的请求没释放掉，建议切换后把之前的实例释放掉，保证请求资源不会被浪费~
> 
> http1同源请求不能超过6 确实太坑了 如果同时播放8路视频 还做不到。 如何把http1 升级为http2 是需要在转发直播流的服务器上做设置吗

对，在用于播放的流媒体服务器上设置，我才折腾完这块。。

**Comment by shady-xia** [comment]
> > > > 1、浏览器http1的同源限制，同源下的http请求同时最多只能有6个，多出来的会pending 2、你切清晰度后，还增加了请求，说明之前的请求没释放掉，建议切换后把之前的实例释放掉，保证请求资源不会被浪费~
> > > 
> > > 
> > > http1同源请求不能超过6 确实太坑了 如果同时播放8路视频 还做不到。 如何把http1 升级为http2 是需要在转发直播流的服务器上做设置吗
> > 
> > 
> > 对，在用于播放的流媒体服务器上设置，我才折腾完这块。。
> 
> 有尝试过web端播放h265视频 播放器性能比较好 能同时支持7-8路视频的 js播放器解决方案吗 不过我现在找到的都是软解码h265 软解码 性能太差 多路很卡 运行内存爆炸

没有实际用过，不过有关注相关的库，你可以研究一下
https://github.com/xqq/mpegts.js
https://github.com/langhuihui/jessibuca
