### ISSUE TITLE
enableWorker 配置错误

### ISSUE THREAD

**Issue by ADZG** [shady-xia/flvExtend#7]
![image](https://user-images.githubusercontent.com/44188873/197751554-f09b7d0c-7bd2-4c8b-b0d1-39ce2146e962.png)
![image](https://user-images.githubusercontent.com/44188873/197751656-5a2153f0-88d0-402e-b84e-6d27047eddaf.png)

**Comment by ADZG** [comment]
环境next.js webpack 似乎是需要cjs环境

**Comment by zzzzzzdk** [comment]
请问现在可以解决了吗

**Comment by ADZG** [comment]
> 请问现在可以解决了吗

解决不了,flv的问题，flv已经不维护了，G了

**Comment by zzzzzzdk** [comment]
> > 请问现在可以解决了吗
> 
> 解决不了,flv的问题，flv已经不维护了，G了

G
