### ISSUE TITLE
frameTrackingDelta参数设置无效

### ISSUE THREAD

**Issue by zhanglin132** [shady-xia/flvExtend#8]
经过验证，发现frameTrackingDelta这个参数无效。类型是boolean？设置true无效，设置成数字类型1也无效。不知道什么原因，请帮忙解答，谢谢。

**Comment by zhanglin132** [comment]
希望frameTrackingDelta和playbackRate都可以进行配置，谢谢。

**Comment by shady-xia** [comment]
frameTrackingDelta是最大延迟时间，类型为number，超过设定的值才会触发追帧，看来是我readme写错了。playbackRate配置会加上。

**Comment by zhanglin132** [comment]
<img width="807" alt="image" src="https://user-images.githubusercontent.com/118363265/202333446-1b54992b-f11d-4926-9231-7d83b9ea3628.png">
这个文件中好像并没有配置frameTrackingDelta。

**Comment by zhanglin132** [comment]
期待早日加上playbackRate配置，谢谢。我不是专业前端，您这个库封装的确实优秀，对我帮助很大。

**Comment by shady-xia** [comment]
已在v0.1.1版本中进行了修改，加上了 `trackingPlaybackRate` 参数，即追帧时的播放速率
另外 `frameTrackingDelta` 参数改名为 `trackingDelta`（旧名称依旧可以用）

**Comment by zhanglin132** [comment]
已验证，OK了
