### ISSUE TITLE
关于追帧

### ISSUE THREAD

**Issue by XiaotaoTTTtian** [shady-xia/flvExtend#9]
想问下老哥在做追帧的时候是基于什么场景下的，因为我这边做用跳帧的话观察到浏览器会把之前的连接给销毁掉，然后重新建立一个新的连接。同时又由于我同时播放八路视频，导致有频繁的白屏出现。为什么不都采用倍速的方式追帧呢？。在延迟过大的时候调为四倍速甚至六倍速播放

**Comment by shady-xia** [comment]
我文章有写，我的思路是延迟小的时候通过倍速来追帧，延迟过大通过倍速就不现实了，比如你切换了页面重新再聚焦，这个时候延迟多大都有可能；
跳帧是不会重新建立连接的，你观察到的应该不是跳帧
